version: "2"
services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - "$PWD:/var/www/html"
      - "$PWD/.docker/backup:/tmp/backup"
      - "$PWD/.docker/log:/tmp/log"
    ports:
      - 80:80
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: "mysql:3306"
    networks:
      - my_wordpress_network
    env_file: .env

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - "db-data:/var/lib/mysql"
    networks:
      - my_wordpress_network
    env_file: .env

volumes:
  db-data:

networks:
  my_wordpress_network:

